USE [NBNData]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SELECT
    TAO.TAXON_OCCURRENCE_KEY AS TAO_TAXON_OCCURRENCE_KEY,
    TAO.COMMENT AS TAO_COMMENT,
    NS.RECOMMENDED_SCIENTIFIC_NAME AS NS_RECOMMENDED_SCIENTIFIC_NAME, 
    NS.RECOMMENDED_NAME_AUTHORITY AS NS_RECOMMENDED_NAME_AUTHORITY, 
    NS.RECOMMENDED_NAME_RANK AS NS_RECOMMENDED_NAME_RANK, 
    SA.VAGUE_DATE_START AS SA_VAGUE_DATE_START, 
    SA.VAGUE_DATE_END AS SA_VAGUE_DATE_END, 
    SA.VAGUE_DATE_TYPE AS SA_VAGUE_DATE_TYPE,
    SUE.COMMENT AS SUE_COMMENT, 
	LN.ITEM_NAME AS LN_ITEM_NAME,
    SUE.LOCATION_NAME AS SUE_LOCATION_NAME,
    SA.LAT AS SA_LAT,
    SA.LONG AS SA_LONG,
    SA.SPATIAL_REF AS SA_SPATIAL_REF,
    SA.SPATIAL_REF_SYSTEM AS SA_SPATIAL_REF_SYSTEM,
    SA.SPATIAL_REF_QUALIFIER AS SA_SPATIAL_REF_QUALIFIER

FROM 
    dbo.SURVEY SU
	INNER JOIN dbo.SURVEY_EVENT SUE ON SUE.SURVEY_KEY = SU.SURVEY_KEY
	INNER JOIN dbo.SAMPLE SA ON SA.SURVEY_EVENT_KEY = SUE.SURVEY_EVENT_KEY
	INNER JOIN dbo.TAXON_OCCURRENCE TAO ON TAO.SAMPLE_KEY = SA.SAMPLE_KEY
	INNER JOIN dbo.TAXON_DETERMINATION TD ON TD.TAXON_OCCURRENCE_KEY = TAO.TAXON_OCCURRENCE_KEY
	INNER JOIN dbo.TAXON_LIST_ITEM TLI ON TLI.TAXON_LIST_ITEM_KEY = TD.TAXON_LIST_ITEM_KEY 
	LEFT OUTER JOIN inbo.NameServer NS ON NS.INBO_TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY
	LEFT OUTER JOIN dbo.TAXON_VERSION TV ON TV.TAXON_VERSION_KEY = TLI.TAXON_VERSION_KEY
	LEFT OUTER JOIN dbo.TAXON T ON T.TAXON_KEY = TV.TAXON_KEY
	INNER JOIN dbo.LOCATION L ON L.LOCATION_KEY = SA.LOCATION_KEY
	INNER JOIN dbo.LOCATION_NAME LN ON LN.LOCATION_KEY = L.LOCATION_KEY
	LEFT JOIN dbo.INDIVIDUAL I ON I.NAME_KEY = TD.DETERMINER

WHERE
	SU.ITEM_NAME = 'Alien macro-invertebrates in Flanders'
	AND LN.PREFERRED = 1
GO


